on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        report: 'true'
        chart: 'true'
        amend: 'false'
      if: |
        matrix.os == 'ubuntu-latest' &&
        github.event_name == 'push'  
      continue-on-error: true
      
    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        report: 'true'
        chart: 'true'
        amend: 'false'
      if: |
        matrix.os == 'ubuntu-latest' &&
        github.event_name == 'push'  
      continue-on-error: true

  test-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...