on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: generate test generate coverage
    run: go test ./... -coverprofile=./cover.out

    - name: check test coverage
      id: coverage ## this step must have id
      uses: vladopajic/go-test-coverage@v2
      with:
        profile: cover.out
        local-prefix: github.com/smallnest/exp
        threshold-file: 80
        threshold-package: 80
        threshold-total: 95
    
    - name: make coverage badge
      uses: action-badges/core@0.2.2
      if: contains(github.ref, 'main')
      with:
        label: coverage
        message: ${{ steps.coverage.outputs.badge-text }}
        message-color: ${{ steps.coverage.outputs.badge-color }}
        file-name: coverage.svg
        badge-branch: badges ## orphan branch where badge will be committed
        github-token: "${{ secrets.GITHUB_TOKEN }}"